### ISSUE TITLE
Draining/Filling tanks to/from held stacks of EnderIO tanks.

### ISSUE THREAD

**Issue by lehjr** [Zarathul/simplefluidtanks#10]
simplefluidtanks-1.8.9-1.3.0.5 / EnderIO-1.8.9-3.0.0.26_alpha

There appears to be an issue with filling/draining with EnderIO tanks when stacked where draining/filling treats the stack as a single item rather than accounting for the number of tanks. For instance, filling all tanks in an empty stack of EnderIO tanks will only drain 16 buckets of fluid from the Simple Fluid Tank rather than multiplying by the number of tanks.  Likewise, draining a stack of EnderIO tanks into the Simple Fluid Tank will only add 16 buckets of fluid into the tank regardless of the stack size, but will drain all of the EnderIO tanks in the stacks. For now, I am unstacking them and draining/filling individually, but it's not ideal.

**Comment by Zarathul** [comment]
Hmm. I'll look into it.

**Comment by Zarathul** [comment]
Seems to me this is more of an oversight on their end (it's a rarely used feature after all). It makes more sense to me to handle this on the item side. Also looking at other mods, Thermal Expansion tanks are not stackable probably partly because of this and OpenBlocks tanks actually correctly distribute to/drain from all tanks in the stack.
So please open a new issue [here](https://github.com/SleepyTrousers/EnderIO/issues) if you haven't already done that.

**Comment by lehjr** [comment]
So basically, "The-Other-Guy" bug on both sides? This bug isn't present when using the EnderIO tanks with Buildcraft tanks though.
