### ISSUE TITLE
No information when hovering over valve

### ISSUE THREAD

**Issue by ZomecGaming** [Zarathul/simplefluidtanks#19]
Hard to tell if there is stuff is even flowing in or not. I have a screenshot which I will try to include [here,](https://photos.app.goo.gl/RC72qLHndQNtxrUi8)  I have no way of know how much is in my tanks. 

I have also tried placing multiple valve's in the past which does not seem to work.

**Comment by Zarathul** [comment]
It would be good to know which version your even talking about. Since there is Buildcraft stuff in the screenshot, I assume it's 1.12.2 and not 1.14.4.

> Hard to tell if there is stuff is even flowing in or not. I have a screenshot which I will try to include here, I have no way of know how much is in my tanks.

Well, first of all you should of course see if the fluid rises in a tank. Besides that, you can use a comparator to get an indication how full a tank is. ![Comparator usage](https://media.forgecdn.net/attachments/4/744/comparator.jpg)
If you need exact numbers, you'll have to use TheOneProbe. I can't tell from your screenshot if that is what you are already using or if it's WAILA. TheOneProbe should work, but also needs to be also installed on the server if you play multiplayer. WAILA is not supported anymore and will most likely only show garbage.

> I have also tried placing multiple valve's in the past which does not seem to work.

That won't work. You can only have one valve per tank. That's an unfortunate side effect of how the tanks work.

**Comment by Zarathul** [comment]
No answer in a week, so I guees this has been resolved.
